// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQmDnikDwBv_x5lFpchpQgaEO-QsCCT8w',
    appId: '1:407898229764:web:d1ee8fea70dd15b1663951',
    messagingSenderId: '407898229764',
    projectId: 'authentication-tut',
    authDomain: 'authentication-tut-6b060.firebaseapp.com',
    storageBucket: 'authentication-tut.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupQuFIjV39_oqfsuNYW9qXEwYKPTp5rE',
    appId: '1:407898229764:android:fc828bc03b7e0a49663951',
    messagingSenderId: '407898229764',
    projectId: 'authentication-tut',
    storageBucket: 'authentication-tut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIi0HFRf75lIi00IM1OqJx4W66tJM7G4',
    appId: '1:407898229764:ios:45c8d4e9499f408b663951',
    messagingSenderId: '407898229764',
    projectId: 'authentication-tut',
    storageBucket: 'authentication-tut.appspot.com',
    iosClientId: '407898229764-fau2h0lo7r7ah4u4i746uhr9m3m2pk1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIi0HFRf75lIi00IM1OqJx4W66tJM7G4',
    appId: '1:407898229764:ios:45c8d4e9499f408b663951',
    messagingSenderId: '407898229764',
    projectId: 'authentication-tut',
    storageBucket: 'authentication-tut.appspot.com',
    iosClientId: '407898229764-fau2h0lo7r7ah4u4i746uhr9m3m2pk1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
